### ISSUE TITLE
Terms that start with a DSCP match will cause parse errors.

### ISSUE THREAD

**Issue by robison** [google/capirca#136] opened 2017-06-10 20:08 UTC
Not 100% certain if this is intentional, but any terms that begin with a potential match for a DSCP marking followed by a hyphen will cause a parse error. e.g.:

    (venv) [13:03:56][ robisonjac-ltm:~/git/github.com/capirca ](✖ master) $ git diff tests/lib/cisco_test.py
    diff --git a/tests/lib/cisco_test.py b/tests/lib/cisco_test.py
    index 72d347b..cc4b918 100644
    --- a/tests/lib/cisco_test.py
    +++ b/tests/lib/cisco_test.py
    @@ -109,13 +109,13 @@ header {
     }
     """
     GOOD_STANDARD_TERM_1 = """
    -term standard-term-1 {
    +term cs5-standard-term-1 {
       address:: SOME_HOST
       action:: accept
     }
     """
     GOOD_STANDARD_TERM_2 = """
    -term standard-term-2 {
    +term cs5standard-term-2 {
       address:: SOME_HOST
       action:: accept
     }
    (venv) [13:04:01][ robisonjac-ltm:~/git/github.com/capirca ](✖ master) $

And upon running pytest, the following error is generated:

    p = LexToken(DSCP,u'cs5',7,84)

        def p_error(p):
          """."""
          next_token = yacc.token()
          if next_token is None:
            use_token = 'EOF'
          else:
            use_token = repr(next_token.value)

          if p:
            raise ParseError(' ERROR on "%s" (type %s, line %d, Next %s)'
    >                        % (p.value, p.type, p.lineno, use_token))
    E       ParseError:  ERROR on "cs5" (type DSCP, line 7, Next u'-')

    lib/policy.py:2328: ParseError

I can provide more details if needed, or would be happy to contribute a potential fix - but I wanted to be certain that this was unintended behavior.

**Comment by ankenyr** [comment] 2017-09-20 20:48
Hi @robison,
Sorry for letting this linger. I wouldn't say this it intended behavior. If you have a fix ready please send it and we can review it.

**Comment by ankenyr** [comment] 2017-10-23 22:39
Did you plan on making a fix for this @robison ?

**Closed** 2018-10-05 21:45 UTC
