### ISSUE TITLE
Python3 Support

### ISSUE THREAD

**Issue by bdlamprecht** [google/capirca#154] opened 2018-07-25 15:46 UTC
I see that issue #110 was opened to ask about support for `python3`, however nothing has changed in that regard even though [this](https://github.com/google/capirca/issues/110#issuecomment-268627557) comment mentioned it would hopefully be migrated by the end of December 2017 at the latest.

It was also mentioned in that comment that some type of mention would be added to the roadmap in the wiki, but I don't see anything there either.

Can someone provide any updates if this is still planned at all?

**Comment by ankenyr** [comment] 2018-07-27 19:35
Thanks for opening this. It completely slipped my mind. The roadmap is not well maintained so I should go through that soon. As for Python3, it should be able to be converted, I need to check on some internal things just to be sure. Let me get back to you on Monday.

**Comment by bdlamprecht** [comment] 2018-07-31 20:25
Sure, thanks for remembering, looking forward to it being supported.

**Comment by ankenyr** [comment] 2018-07-31 20:39
Gah sorry I didn't update this yesterday. Working on some stuff for #116 still.
I don't see anything that should be preventing us from doing this. I need to get #116 finished and then I can work on this.

**Comment by bdlamprecht** [comment] 2018-08-16 14:55
Any updates on this issue yet?

**Comment by ankenyr** [comment] 2018-08-17 00:33
No big updates, there are some issues that will need to be resolved.
1) Changing over to python3 will break some internal stuff, nothing super important nor that doesn't have a workaround but I will need to work with a couple of teams on relevant issues, make an announcement to our internal users, etc
2) There are a few incompatibilities that need to be fixed in the mean time such as removing the reliance on dircache and other libraries that are not in python3.
Please feel free to keep pinging this issue to ask for status updates but I expect a few CLs to be coming out over the next few weeks and will try to aim to be complete by the end of next month.

**Comment by bdlamprecht** [comment] 2018-08-17 18:38
Okay, thanks for the response.

As you mentioned, I'll try and keep "pinging" this issue every 2-3 weeks as a reminder.

**Comment by bdlamprecht** [comment] 2018-10-02 18:01
@ankenyr It has been almost 2 months since the last time I "pinged" about this issue.
Are there any updates you have to share?

**Comment by ankenyr** [comment] 2018-10-02 18:36
Currently we are blocked on https://github.com/google/capirca/issues/159 which is referenced just above your last post. As I said on that issue I am expecting to be able to push out that change tomorrow and I am still on schedule with that.

**Comment by ankenyr** [comment] 2019-01-08 19:59
Sorry about the long lull, working on some other things within capirca for the time being. Internally there are a few things that are a blocker for moving to python 3 that are outside of my control. I expect these issues to be resolved by the end of the quarter.

**Comment by XioNoX** [comment] 2019-04-04 22:20
Ping? Thanks :)

**Comment by ankenyr** [comment] 2019-04-15 20:54
Hey, thanks for pinging this and reminding me. I just checked and it looks like we are finally at 3.5 which if I remember is the minimum version we need for the incompatibilities if ipaddress to be resolved. I have some code I need to finish for another project that is nearing completion. I expect I should be able to get started on this in the next few days. If you do not hear anything on this by Friday please feel free to ping this again to get my attention.

**Comment by ankenyr** [comment] 2019-04-17 22:00
So I created the initial change to move things to python3. The following are a list of general changes I have made so far.

- Across all libraries, removed unicode related specifics
- CloudArmor: Using range instead of xrange
- gce: Adding name to skip attributes
- nacaddr: Adding a method only available in 3.7, this is to be removed once we can
- nsxv: Removing the UTF-8 encoding in __str__, __str__ must return a string and UTF-8 is a byte object. TODO added to fix this.
- policy: adding __hash__ method, fixing how parser works passing "1:" indexing into p.slice
- tests have assertItemsEqual moved to assertListEqual

Once I can get these submitted I will wait for internal partner teams to integrate the change. Once I can confirm there are no big issues that would require a rollback I can migrate this change out to Github.

This will be a bit of a race, I am expecting a child in the next couple weeks so as soon as she is born I plan on taking a month of my paternity leave. If this happens before I can make sure there are no internal issues related to this migration I will try and get a coworker to push out the change to Github.

**Comment by ankenyr** [comment] 2019-04-30 23:18
Code took a bit longer to review than I intended but it landed just now. Will give it a few days to make sure nothing comes out from the woodworks. I will then attempt to push to github.

**Comment by ankenyr** [comment] 2019-05-03 18:40
Ok so the latest commits should make things py3 compatible. Only tested with 3.5 at the moment. Package has been uploaded to pypi with a new version. Tested out installing via pip and setup.py in a virtual env. I am going to consider this closed unless someone finds a problem.

**Closed by ankenyr** 2019-05-03 18:40 UTC

**Comment by bdlamprecht** [comment] 2019-05-08 16:37
Great, thanks for continuing to work on this FR over the past ~1 year!

Unfortunately, I don't have a lot of time to test it out right now.
Once I do, I'll report back with anything that I find.
